CREATE DATABASE credit_risk_db;
USE credit_risk_db;
CREATE TABLE IF NOT EXISTS credit_risk_data (
    SK_ID_CURR BIGINT,
    TARGET INT,
    AMT_INCOME_TOTAL DOUBLE,
    AMT_CREDIT DOUBLE,
    AMT_ANNUITY DOUBLE,
    AMT_GOODS_PRICE DOUBLE,
    DAYS_BIRTH INT,
    DAYS_EMPLOYED DOUBLE,
    CODE_GENDER VARCHAR(20),
    NAME_EDUCATION_TYPE VARCHAR(100),
    NAME_FAMILY_STATUS VARCHAR(100),
    NAME_INCOME_TYPE VARCHAR(100),
    NAME_HOUSING_TYPE VARCHAR(100),
    OCCUPATION_TYPE VARCHAR(100),
    ORGANIZATION_TYPE VARCHAR(100),
    EXT_SOURCE_1 DOUBLE,
    EXT_SOURCE_2 DOUBLE,
    EXT_SOURCE_3 DOUBLE,
    CREDIT_INCOME_RATIO DOUBLE,
    ANNUITY_INCOME_RATIO DOUBLE,
    BUREAU_COUNT DOUBLE,
    BUREAU_CREDIT_MEAN DOUBLE,
    BUREAU_CREDIT_MAX DOUBLE,
    PREV_APPLICATION_COUNT DOUBLE,
    PREV_APPLICATION_MEAN DOUBLE,
    PREV_CREDIT_MEAN DOUBLE,
    PREV_CREDIT_MAX DOUBLE,
    AGE_YEARS DOUBLE
);
SHOW TABLES;
DESCRIBE credit_risk_data;
SELECT COUNT(*) AS total_rows
FROM credit_risk_data;